language: node_js
node_js:
- 8.2.1
services:
- docker
notifications:
  email:
  - relfishere@gmail.com
  - okanvurdu@gmail.com
  - frknbasaran@gmail.com
script:
- cd src
- docker build -t web .
- docker tag web:latest $DOCKER_HUB_USERNAME/web:prod
- docker push $DOCKER_HUB_USERNAME/web:prod
env:
  global:
  - secure: lzRIjynA3mP7H93Cnq2G4o3GLjCMSK9Zh5vqjgeKgZ7wvOZJ9lNgVFWf187PHB463zWK+DjaNUOZtqj2PWb/W9+LV1iFOGnbZ10/LyddlxW4Ef5W2GHHMbU0cSI5h4QPCfphZWXDhC0Du/v9LXARxRBtrA9VwQRl2fMWqbJ4Fl9/F1qn/DXBH3on9fa/Cgl2h8UlVlbDep7m7sAPVIo+miHPQcp8KJFfbVtqaisq+ehjwcJiEjxOZfkVxeUNsvLsuhCbx8LoIidbfu7oSNb1yqCP1Bpw2KVZlr6RroHV0CJJ/d4SV5T+G88NwP7O1sZyNFhG1UABURHsaKljnCdD7VaOzW2s8fl3V91ApJn3upawuOAX90hd0LdMERCnVS7I5t9pd7B/JUzqpBWf+yCL/1UcsXbdxynYjjWe2IPgnb3VWwuUzo3WfNOUh8JuDQgQ1wtJcq+D7QVS1z1LoioV2Ln/zeF1wSJXoQPh5F9vDLM8X7lKSbdX265i8FPMyZ6n2xOBi52ObZNsq4CAphlOM3uDycJbXYJF5+NmZq8SYxLfrvdJ6gXxV3MOeptV+PvJ00SjjGVLwJ+1UJIFqu3/qC0b0X/Fm+O+lLK/guFSgvVcY+Cw51gJhzhaTYa+1GNwIXUKp2+sOHyDZQKF2ismXjBEhKvZe5DRD/eql0Cruns=
  - secure: V0r2k44j5UE6JIAPwG5WQewUsWTAQprYycWbQHVjCKbacAtgymT719eD7qpnYP9KGtkDd5Z26K9c+3T1ZL3MDW4xj+GGGxk81Xkfd416n56HUpzcPPc5pvFFs7/UyMI3fwdH1RTH6L1CI+j3m2CF0lhOaMeNnM9g5u7Is8WRO/N4lJYJqGPb8KB7BajNTcdtTF1DOhbaISv4ItoiqRLwYJawhxFYRi9g2nL3nMO9fN6Z/bergO14CMOU7hFnDvw3CaEyDBC7ewf7z2uPzsHKLxcVjvCgpYYulPfTaWXmDMPcTdX22cHaB4OIbIo4YJqZYo8drIhp+FFNDPFr6iWGy9r0igoGlHm5oFcjdY7pJuVbwL9KnW944h/LE+rtqvUPf2OS7Y1MXcq+Ee8U8frajUXVCYyJ1KMCbVXZ0ZXBbEIYYdvTcQR6P6g6WKDAIDIZTpKkFMJtASE4TlOgNz5fTv45xAF2OwBlrPt0NbKWuL1ZaQXyb/pbCaQZRPp+RWC7kpHLuBBlSuaMBaL56cd67lzaw/m6wbUQewehQ4gKJRm1WMTofoQSPnrmU3wRO8YkEYg0wyUpeCSz0Xk7rHK0QAtFVZL4ZmXEeUYayLXxZvWsSNHQxldRdVXNDdA5qH/P9Oz59Y7mjL2ArCatZP8J1zjdxOFrHvfDu+LmMzt+j20=
  - SOZLUK_ENV=test
before_install:
- docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
- openssl aes-256-cbc -K $encrypted_aa5f2cc2971c_key -iv $encrypted_aa5f2cc2971c_iv
 -in deploy_key.enc -out ./deploy_key -d
- docker build -t webtest .
deploy:
 provider: script
 skip_cleanup: true
 script: cd .. && chmod 400 deploy_key && ssh -o StrictHostKeyChecking=no -i deploy_key -p 2222 ubuntu@sausozluk.net "cd sozluk && ./deploy.sh"
 on:
   branch: master
